### ISSUE TITLE
Kapitel 5.4.4 Mit Zeitfenstern arbeiten

### ISSUE THREAD

**Issue by eiler-partner** [tplusone/hanser_ml_zeitreihen#1]
Hallo Herr Hirschle,

Könnten Sie bitte für Kapitel 5.4.4 den Code und die Daten für die Simulation des Stromverbrauchs zur Verfügung stellen?
Danke!
MfG
Patrick Eiler

**Comment by tplusone** [comment]
Hallo Herr Eiler,
ja, gerne. Ich hab den Code und die Daten inzwischen hochgeladen (unter Kapitel_5_DeepLearning/5_4_Rekurrente_Netze ist das Notebook "b_Stromverbrauch_Kapitel_544.ipynb" hinterlegt).
Viele Grüße,
Jochen Hirschle

**Comment by eiler-partner** [comment]
Vielen Dank und Grüße!
Patrick Eiler
