### ISSUE TITLE
Kapitel 5.6.2 Zeitfenster mit Generartor anlernen

### ISSUE THREAD

**Issue by eiler-partner** [tplusone/hanser_ml_zeitreihen#2]
Sehr geehrter Herr Dr. Hirschle,
Ich habe das Beispiel für die Temperatur in Jena nachgestellt.
Mit ein paar kleinen Korrekturen bekomme ich das Ergebnis, welches aber vom Buch um einen Faktor 10 abweicht.
Habe ich in Code etwas übersehen.
Wenn es möglich ist, bitte ich Sie um ihren Code.
Vielen Dank
Patrick Eiler
[Temp_Prog_Jena.zip](https://github.com/tplusone/hanser_ml_zeitreihen/files/6067363/Temp_Prog_Jena.zip)

**Comment by tplusone** [comment]
Hallo Herr Eiler,
ihr Code sieht gut aus - das einzige Problem ist wohl, dass Sie beim Anlernen versehentlich mit den unstandardisierten y-Daten arbeiten (y_train statt y_train_std, y_test statt y_test_sd). Deshalb schätzt ihr Modell seltsame Werte (weil die Funktion predictions_vs_true annimmt, dass die Werte standardisiert sind und mit inverse_transform die Standardisierung wieder rückgängig gemacht wird).
Ich hab außerdem den Orginalcode aus dem Buch inzwischen hochgeladen (im Ordner 5.6 Zeitfenster in der Praxis).
Viele Grüße
Jochen Hirschle

**Comment by eiler-partner** [comment]
Super!
Vielen Dank. Verstanden.

Übrigens, Kapitel 4 ARIMA finde ich sehr gut, wenn auch knapp erklärt.
Habe Chatfield 1995 gelernt und auch die Unterscheidung mit den AC und PAC für die Modelselektion ist gut dargestellt.
Danke, dass Sie dieses Thema mit Python hier darstellen.
Viele Grüße
Patrick Eiler
