### ISSUE TITLE
Beispiel 5.2.3 zu "sparse_categorical_crossentropy" fehlt

### ISSUE THREAD

**Issue by mazl-io** [tplusone/hanser_ml_zeitreihen#3]
Hallo Jochen,

hast du den Code zu dem in deinem Buch unter 5.2.3 geführten Beispiel mit der sparse_categorical_crossentropy evtl. noch?

Ich komme hier mit den Snippets aus dem Buch leider nicht weiter.

Vielen Dank und viele Grüße
Marcel

**Comment by tplusone** [comment]
Hallo Marcel,

ja, kein Problem, ich hab den Code hochgeladen und die Daten zur Verfügung gestellt. Die Daten sind übrigens mit einer Funktion aus Scikit-Learn künstlich erzeugt worden, daher wahrscheinlich die Verwirrung.
Ich hoffe, jetzt klappt alles. Du findest das neue Notebook unter Kapitel_5_DeepLearning/5_2_Einfache_Modelle_mit_Keras_aufbauen/c_Anlernprozess_steuern

Alles Gute und viele Grüße,
Jochen

**Comment by mazl-io** [comment]
Hi Jochen, spitze, vielen Dank!
Ich hab in der Zwischenzeit auch schon etwas dazu gelernt und dein Code bestätigt meinen Denkfehler!

Die "Classes", also Kategorien die vorhergesagt werden sollen, müssen scheinbar unsigned sein, d.h. ab 0 beginnend +=1 aufsteigend sein. Ich hatte eine Skala von -6 bis +6, wodurch ich leider immer "NaN"-Predictions bekommen habe.

Weiter gehts, vielen Dank nochmal! :)
